name: Check Submodule Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Check for devops-java submodule changes
        id: check_changes
        run: |
          git submodule update --recursive
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            if git diff --quiet HEAD^ HEAD -- devops-java; then
              echo "No changes in devops-java submodule"
              exit 0
            else
              echo "Changes detected in devops-java submodule"
              exit 1
            fi
          else
            echo "No previous commit found. Skipping diff check."
            exit 0
          fi

      - name: Trigger main workflows
        if: steps.check_changes.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const workflowId = workflows.workflows.find(w => w.name === 'Build and Deploy').id;
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              ref: context.ref,
              inputs: {
                submodule: 'devops-java',
              },
            });
