name: Check Submodule Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Check for devops-java submodule changes
        id: check_changes
        run: |
          git submodule update --recursive
          if git diff --quiet HEAD^ HEAD -- devops-java; then
            echo "No changes in devops-java submodule"
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "Changes detected in devops-java submodule"
            echo "changes_detected=true" >> $GITHUB_ENV
          fi
        shell: /usr/bin/bash -e {0}

      - name: Trigger main workflows
        if: env.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const workflowId = workflows.workflows.find(w => w.name === 'Build and Deploy').id;
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              ref: context.ref,
              inputs: {
                submodule: 'devops-java',
              },
            });
