name: Check Submodule Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Check for devops-java submodule changes
        id: check_changes
        run: |
          git submodule update --recursive
          if git diff --quiet HEAD^ HEAD -- devops-java; then
            echo "No changes in devops-java submodule"
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "Changes detected in devops-java submodule"
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Trigger Build and Deploy Workflow
        if: env.changes_detected == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            const workflow_id = 'build-and-deploy.yml'; // name of the reusable workflow file
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
              ref: context.ref,
              inputs: {
                submodule: 'devops-java',
              },
            });
